# Generated by Django 4.2.5 on 2023-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CorporateAssetApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettrack",
            name="returned_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
